require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BancWheresController do

  # This should return the minimal set of attributes required to create a valid
  # BancWhere. As you add validations to BancWhere, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "n_rue" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BancWheresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all banc_wheres as @banc_wheres" do
      banc_where = BancWhere.create! valid_attributes
      get :index, {}, valid_session
      assigns(:banc_wheres).should eq([banc_where])
    end
  end

  describe "GET show" do
    it "assigns the requested banc_where as @banc_where" do
      banc_where = BancWhere.create! valid_attributes
      get :show, {:id => banc_where.to_param}, valid_session
      assigns(:banc_where).should eq(banc_where)
    end
  end

  describe "GET new" do
    it "assigns a new banc_where as @banc_where" do
      get :new, {}, valid_session
      assigns(:banc_where).should be_a_new(BancWhere)
    end
  end

  describe "GET edit" do
    it "assigns the requested banc_where as @banc_where" do
      banc_where = BancWhere.create! valid_attributes
      get :edit, {:id => banc_where.to_param}, valid_session
      assigns(:banc_where).should eq(banc_where)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BancWhere" do
        expect {
          post :create, {:banc_where => valid_attributes}, valid_session
        }.to change(BancWhere, :count).by(1)
      end

      it "assigns a newly created banc_where as @banc_where" do
        post :create, {:banc_where => valid_attributes}, valid_session
        assigns(:banc_where).should be_a(BancWhere)
        assigns(:banc_where).should be_persisted
      end

      it "redirects to the created banc_where" do
        post :create, {:banc_where => valid_attributes}, valid_session
        response.should redirect_to(BancWhere.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved banc_where as @banc_where" do
        # Trigger the behavior that occurs when invalid params are submitted
        BancWhere.any_instance.stub(:save).and_return(false)
        post :create, {:banc_where => { "n_rue" => "invalid value" }}, valid_session
        assigns(:banc_where).should be_a_new(BancWhere)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BancWhere.any_instance.stub(:save).and_return(false)
        post :create, {:banc_where => { "n_rue" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested banc_where" do
        banc_where = BancWhere.create! valid_attributes
        # Assuming there are no other banc_wheres in the database, this
        # specifies that the BancWhere created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BancWhere.any_instance.should_receive(:update).with({ "n_rue" => "1" })
        put :update, {:id => banc_where.to_param, :banc_where => { "n_rue" => "1" }}, valid_session
      end

      it "assigns the requested banc_where as @banc_where" do
        banc_where = BancWhere.create! valid_attributes
        put :update, {:id => banc_where.to_param, :banc_where => valid_attributes}, valid_session
        assigns(:banc_where).should eq(banc_where)
      end

      it "redirects to the banc_where" do
        banc_where = BancWhere.create! valid_attributes
        put :update, {:id => banc_where.to_param, :banc_where => valid_attributes}, valid_session
        response.should redirect_to(banc_where)
      end
    end

    describe "with invalid params" do
      it "assigns the banc_where as @banc_where" do
        banc_where = BancWhere.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BancWhere.any_instance.stub(:save).and_return(false)
        put :update, {:id => banc_where.to_param, :banc_where => { "n_rue" => "invalid value" }}, valid_session
        assigns(:banc_where).should eq(banc_where)
      end

      it "re-renders the 'edit' template" do
        banc_where = BancWhere.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BancWhere.any_instance.stub(:save).and_return(false)
        put :update, {:id => banc_where.to_param, :banc_where => { "n_rue" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested banc_where" do
      banc_where = BancWhere.create! valid_attributes
      expect {
        delete :destroy, {:id => banc_where.to_param}, valid_session
      }.to change(BancWhere, :count).by(-1)
    end

    it "redirects to the banc_wheres list" do
      banc_where = BancWhere.create! valid_attributes
      delete :destroy, {:id => banc_where.to_param}, valid_session
      response.should redirect_to(banc_wheres_url)
    end
  end

end
